# -*- coding: utf-8 -*-
"""Модуль локализации для приложения School Bell"""

LOCALIZATION = {
    "ru": {
        "app_title": "Школьные звонки",
        "menu_file": "Файл",
        "menu_settings": "Настройки",
        "menu_edit": "Редактировать",
        "menu_help": "Справка",
        "action_load": "Загрузить расписание",
        "action_save": "Сохранить расписание",
        "action_export_settings": "Экспорт всех настроек...",
        "action_import_settings": "Импорт всех настроек...",
        "action_exit": "Выход",
        "action_sounds": "Мелодии звонков...",
        "menu_sounds": "Мелодии звонков",
        "action_music": "Музыка на переменах",
        "action_anthem": "Гимн",
        "action_announcement": "Объявления",
        "action_templates": "Редактор шаблонов",
        "menu_language": "Язык",
        "action_today": "Сегодня",
        "action_locale_ru": "Русский",
        "action_locale_en": "English",
        "action_about": "О программе",
        "btn_edit": "Ред.расписание",
        "status_ready": "Готов к работе",
        "status_lessons_finished": "Уроки закончились",
        "bell_settings_saved": "Мелодии звонков обновлены",
        "chk_bells": "Звонки",
        "chk_music": "Музыка на переменах",
        "chk_anthem": "Гимн",
        "chk_announcement": "Объявления",
        "volume_group": "Громкость",
        "volume_bell": "Звонок",
        "volume_music": "Музыка",
        "volume_anthem": "Гимн",
        "volume_announcement": "Объявление",
        "btn_today": "📅 Сегодня",
        "btn_bell": "🔔 Звонок",
        "btn_music": "🎵 Музыка",
        "btn_anthem": "🎼 Гимн",
        "btn_announcement": "📢 Объявление",
        "btn_stop": "🛑 Стоп",
        "btn_yes": "Да",
        "btn_no": "Нет",
        "btn_cancel": "Отмена",
        "no_schedule": "Нет",
        "col_start": "Начало",
        "col_end": "Конец",
        "col_break": "Перемена",
        "min": "мин",
        "error_title": "Ошибка",
        "export_settings_title": "Экспорт всех настроек",
        "export_settings_done": "Настройки успешно экспортированы",
        "import_settings_done": "Настройки успешно импортированы",
        "confirm_exit_title": "Подтверждение выхода",
        "confirm_exit_text": "Вы уверены, что хотите выйти из программы?",
        "close_to_tray_title": "Закрыть программу?",
        "close_to_tray_text": "Оставить программу в трее, чтобы расписание продолжало работать?",
        "close_to_tray_stay": "Остаться в трее",
        "close_to_tray_exit": "Выйти",
        "minimized_to_tray": "Приложение свернуто в трей",
        "missing_bell_sound": "Мелодия звонка не выбрана или не найдена. Выберите звук в настройках.",
        "missing_music_folder": "Папка с музыкой не выбрана или не найдена. Выберите папку в настройках.",
        "missing_music_tracks": "В выбранной папке нет аудиофайлов.",
        "missing_anthem_file": "Файл гимна не выбран или не найден. Выберите файл в настройках.",
        "missing_anthem_schedule": "День или время гимна не заданы. Проверьте настройки гимна.",
        "missing_announcement_file": "Файл объявления не выбран или не найден. Выберите файл в настройках.",
        "missing_announcement_schedule": "Дата или время объявления не заданы. Проверьте настройки объявления.",
        "announcement_playing": "Сейчас воспроизводится объявление. Музыка не будет запущена.",
        "about_title": "О программе",
        "about_text": "<h2>Школьные звонки</h2>"
                        "<p>Автоматизация школьных звонков с гибким расписанием, музыкой на переменах и гимном и объявлениями.</p>"
                        "<p><b>Версия:</b> 1.0</p>"
                        "<p><b>Репозиторий GitHub:</b> <a href='https://github.com/otetswoo/python_schoolbell'>github.com/otetswoo/python_schoolbell</a></p>"
                        "<p><b>Лицензия:</b> MIT</p>",
        "action_profiles": "Профили расписания...",
        "profiles_dialog_title": "Профили расписания",
        "profiles_info": "Управляйте профилями расписания. Активируйте нужный профиль для применения его настроек.",
        "btn_add": "Добавить",
        "btn_rename": "Переименовать",
        "btn_delete": "Удалить",
        "btn_activate": "Активировать",
        "btn_close": "Закрыть",
        "add_profile_title": "Добавить профиль",
        "add_profile_label": "Введите имя профиля:",
        "profile_exists": "Профиль с таким именем уже существует",
        "cannot_rename_default": "Нельзя переименовать профиль 'default'",
        "rename_profile_title": "Переименовать профиль",
        "rename_profile_label": "Введите новое имя:",
        "confirm_delete_title": "Подтверждение удаления",
        "confirm_delete_text": "Вы уверены, что хотите удалить профиль '{0}'?",
        "delete_failed": "Не удалось удалить профиль",
        "cannot_delete_default": "Нельзя удалить профиль 'default'",
        "success_title": "Успешно",
        "profile_activated": "Профиль '{0}' активирован",
        "action_log": "Журнал событий...",
        "log_dialog_title": "Журнал событий",
        "btn_today_log": "Сегодня",
        "btn_errors_log": "Ошибки",
        "no_events": "Нет событий для отображения",
        "announcements_dialog_title": "📢 Объявления",
        "btn_add_announcement": "➕ Добавить",
        "btn_edit_announcement": "✏️ Изменить",
        "btn_delete_announcement": "🗑️ Удалить",
        "ann_col_file": "Файл",
        "ann_col_date": "Дата",
        "ann_col_time": "Время",
        "ann_col_status": "Статус",
        "ann_status_played": "✅ Сыграно",
        "ann_status_pending": "⏳ Ожидает",
        "ann_status_disabled": "⏸ Выкл",
        "ann_edit_title": "✏️ Редактирование объявления",
        "ann_add_title": "➕ Добавление объявления",
        "ann_active": "Активно",
    },
    "en": {
        "app_title": "School Bell",
        "menu_file": "File",
        "menu_settings": "Settings",
        "menu_edit": "Edit",
        "menu_help": "Help",
        "action_load": "Load Schedule",
        "action_save": "Save Schedule",
        "action_export_settings": "Export all settings...",
        "action_import_settings": "Import all settings...",
        "action_exit": "Exit",
        "action_sounds": "Bell melodies...",
        "menu_sounds": "Bell Melodies",
        "action_music": "Break Music",
        "action_anthem": "Anthem",
        "action_announcement": "Announcements",
        "action_templates": "Templates Editor",
        "menu_language": "Language",
        "action_today": "Today",
        "action_locale_ru": "Russian",
        "action_locale_en": "English",
        "action_about": "About",
        "btn_edit": "Edit Schedule",
        "status_ready": "Ready",
        "status_lessons_finished": "Lessons are finished",
        "bell_settings_saved": "Bell melodies updated",
        "chk_bells": "Bells",
        "chk_music": "Break Music",
        "chk_anthem": "Anthem",
        "chk_announcement": "Announcements",
        "volume_group": "Volume",
        "volume_bell": "Bell",
        "volume_music": "Music",
        "volume_anthem": "Anthem",
        "volume_announcement": "Announcement",
        "btn_today": "📅 Today",
        "btn_bell": "🔔 Bell",
        "btn_music": "🎵 Music",
        "btn_anthem": "🎼 Anthem",
        "btn_announcement": "📢 Announcement",
        "btn_stop": "🛑 Stop",
        "btn_yes": "Yes",
        "btn_no": "No",
        "btn_cancel": "Cancel",
        "no_schedule": "No",
        "col_start": "Start",
        "col_end": "End",
        "col_break": "Break",
        "min": "min",
        "error_title": "Error",
        "export_settings_title": "Export all settings",
        "export_settings_done": "Settings exported successfully",
        "import_settings_done": "Settings imported successfully",
        "confirm_exit_title": "Confirm Exit",
        "confirm_exit_text": "Are you sure you want to exit the program?",
        "close_to_tray_title": "Close the program?",
        "close_to_tray_text": "Keep the program in the tray so the schedule continues to work?",
        "close_to_tray_stay": "Stay in tray",
        "close_to_tray_exit": "Exit",
        "minimized_to_tray": "Application minimized to tray",
        "missing_bell_sound": "Bell melody is not selected or was not found. Choose a sound in settings.",
        "missing_music_folder": "Music folder is not selected or was not found. Choose a folder in settings.",
        "missing_music_tracks": "The selected music folder has no audio files.",
        "missing_anthem_file": "Anthem file is not selected or was not found. Choose a file in settings.",
        "missing_anthem_schedule": "Anthem day or time is not set. Check anthem settings.",
        "missing_announcement_file": "Announcement file is not selected or was not found. Choose a file in settings.",
        "missing_announcement_schedule": "Announcement date or time is not set. Check announcement settings.",
        "announcement_playing": "An announcement is playing now. Music will not start.",
        "about_title": "About",
        "about_text": "<h2>School Bell</h2>"
                        "<p>School bell automation with flexible schedule, break music anthem and announcements.</p>"
                        "<p><b>Version:</b> 1.0</p>"
                        "<p><b>GitHub Repository:</b> <a href='https://github.com/otetswoo/python_schoolbell'>github.com/otetswoo/python_schoolbell</a></p>"
                        "<p><b>License:</b> MIT</p>",
        "action_profiles": "Schedule Profiles...",
        "profiles_dialog_title": "Schedule Profiles",
        "profiles_info": "Manage schedule profiles. Activate a profile to apply its settings.",
        "btn_add": "Add",
        "btn_rename": "Rename",
        "btn_delete": "Delete",
        "btn_activate": "Activate",
        "btn_close": "Close",
        "add_profile_title": "Add Profile",
        "add_profile_label": "Enter profile name:",
        "profile_exists": "A profile with this name already exists",
        "cannot_rename_default": "Cannot rename 'default' profile",
        "rename_profile_title": "Rename Profile",
        "rename_profile_label": "Enter new name:",
        "confirm_delete_title": "Confirm Delete",
        "confirm_delete_text": "Are you sure you want to delete profile '{0}'?",
        "delete_failed": "Failed to delete profile",
        "cannot_delete_default": "Cannot delete 'default' profile",
        "success_title": "Success",
        "profile_activated": "Profile '{0}' activated",
        "action_log": "Event Log...",
        "log_dialog_title": "Event Log",
        "btn_today_log": "Today",
        "btn_errors_log": "Errors",
        "no_events": "No events to display",
        "announcements_dialog_title": "📢 Announcements",
        "btn_add_announcement": "➕ Add",
        "btn_edit_announcement": "✏️ Edit",
        "btn_delete_announcement": "🗑️ Delete",
        "ann_col_file": "File",
        "ann_col_date": "Date",
        "ann_col_time": "Time",
        "ann_col_status": "Status",
        "ann_status_played": "✅ Played",
        "ann_status_pending": "⏳ Pending",
        "ann_status_disabled": "⏸ Disabled",
        "ann_edit_title": "✏️ Edit Announcement",
        "ann_add_title": "➕ Add Announcement",
        "ann_active": "Active",
    }
}
