# -*- coding: utf-8 -*-
"""Модуль локализации для приложения School Bell"""

LOCALIZATION = {
    "ru": {
        "app_title": "Школьные звонки",
        "menu_file": "Файл",
        "menu_settings": "Настройки",
        "menu_edit": "Редактировать",
        "menu_help": "Справка",
        "action_load": "Загрузить расписание",
        "action_save": "Сохранить расписание",
        "action_exit": "Выход",
        "action_sounds_start": "На урок",
        "action_sounds_end": "С урока",
        "menu_sounds": "Мелодии звонков",
        "action_music": "Музыка на переменах",
        "action_anthem": "Гимн",
        "action_announcement": "Объявления",
        "action_locale_ru": "Русский",
        "action_locale_en": "English",
        "action_about": "О программе",
        "btn_edit": "Редактировать расписание",
        "status_ready": "Готов к работе",
        "chk_bells": "Звонки",
        "chk_music": "Музыка на переменах",
        "chk_anthem": "Гимн",
        "chk_announcement": "Объявления",
        "volume_group": "Громкость",
        "volume_bell": "Звонок",
        "volume_music": "Музыка",
        "volume_anthem": "Гимн",
        "volume_announcement": "Объявления",
        "btn_today": "📅 Сегодня",
        "btn_bell": "🔔 Звонок",
        "btn_music": "🎵 Музыка",
        "btn_anthem": "🎼 Гимн",
        "btn_announcement": "📢 Объявление",
        "btn_stop": "🛑 Стоп",
        "btn_yes": "Да",
        "btn_no": "Нет",
        "confirm_exit_title": "Подтверждение выхода",
        "confirm_exit_text": "Вы уверены, что хотите выйти из программы?",
        "close_to_tray_title": "Закрыть программу?",
        "close_to_tray_text": "Оставить программу в трее, чтобы расписание продолжало работать?",
        "close_to_tray_stay": "Остаться в трее",
        "close_to_tray_exit": "Выйти",
        "minimized_to_tray": "Приложение свернуто в трей",
        "missing_bell_sound": "Мелодия звонка не выбрана или не найдена. Выберите звук в настройках.",
        "missing_music_folder": "Папка с музыкой не выбрана или не найдена. Выберите папку в настройках.",
        "missing_music_tracks": "В выбранной папке нет аудиофайлов.",
        "missing_anthem_file": "Файл гимна не выбран или не найден. Выберите файл в настройках.",
        "missing_anthem_schedule": "День или время гимна не заданы. Проверьте настройки гимна.",
        "missing_announcement_file": "Файл объявления не выбран или не найден. Выберите файл в настройках.",
        "missing_announcement_schedule": "Дата или время объявления не заданы. Проверьте настройки объявления.",
        "announcement_playing": "Сейчас воспроизводится объявление. Музыка не будет запущена.",
        "about_title": "О программе",
        "about_text": "<h2>Школьные звонки</h2>"
                        "<p>Автоматизация школьных звонков с гибким расписанием, музыкой на переменах и темами оформления.</p>"
                        "<p><b>Версия:</b> 1.0</p>"
                        "<p><b>Репозиторий GitHub:</b> <a href='https://github.com/otetswoo/python_schoolbell'>github.com/otetswoo/python_schoolbell</a></p>"
                        "<p><b>Лицензия:</b> MIT</p>",
    },
    "en": {
        "app_title": "School Bell",
        "menu_file": "File",
        "menu_settings": "Settings",
        "menu_edit": "Edit",
        "menu_help": "Help",
        "action_load": "Load Schedule",
        "action_save": "Save Schedule",
        "action_exit": "Exit",
        "action_sounds_start": "Start Lesson",
        "action_sounds_end": "End Lesson",
        "menu_sounds": "Bell Melodies",
        "action_music": "Break Music",
        "action_anthem": "Anthem",
        "action_announcement": "Announcements",
        "action_locale_ru": "Русский",
        "action_locale_en": "English",
        "action_about": "About",
        "btn_edit": "Edit Schedule",
        "status_ready": "Ready",
        "chk_bells": "Bells",
        "chk_music": "Break Music",
        "chk_anthem": "Anthem",
        "chk_announcement": "Announcements",
        "volume_group": "Volume",
        "volume_bell": "Bell",
        "volume_music": "Music",
        "volume_anthem": "Anthem",
        "volume_announcement": "Announcements",
        "btn_today": "📅 Today",
        "btn_bell": "🔔 Bell",
        "btn_music": "🎵 Music",
        "btn_anthem": "🎼 Anthem",
        "btn_announcement": "📢 Announcement",
        "btn_stop": "🛑 Stop",
        "btn_yes": "Yes",
        "btn_no": "No",
        "confirm_exit_title": "Confirm Exit",
        "confirm_exit_text": "Are you sure you want to exit the program?",
        "close_to_tray_title": "Close the program?",
        "close_to_tray_text": "Keep the program in the tray so the schedule continues to work?",
        "close_to_tray_stay": "Stay in tray",
        "close_to_tray_exit": "Exit",
        "minimized_to_tray": "Application minimized to tray",
        "missing_bell_sound": "Bell melody is not selected or was not found. Choose a sound in settings.",
        "missing_music_folder": "Music folder is not selected or was not found. Choose a folder in settings.",
        "missing_music_tracks": "The selected music folder has no audio files.",
        "missing_anthem_file": "Anthem file is not selected or was not found. Choose a file in settings.",
        "missing_anthem_schedule": "Anthem day or time is not set. Check anthem settings.",
        "missing_announcement_file": "Announcement file is not selected or was not found. Choose a file in settings.",
        "missing_announcement_schedule": "Announcement date or time is not set. Check announcement settings.",
        "announcement_playing": "An announcement is playing now. Music will not start.",
        "about_title": "About",
        "about_text": "<h2>School Bell</h2>"
                        "<p>School bell automation with flexible schedule, break music and themes.</p>"
                        "<p><b>Version:</b> 1.0</p>"
                        "<p><b>GitHub Repository:</b> <a href='https://github.com/otetswoo/python_schoolbell'>github.com/otetswoo/python_schoolbell</a></p>"
                        "<p><b>License:</b> MIT</p>",
    }
}
